version: '3'

services:
  red-app:
    build:
      context: ./red
      dockerfile: Dockerfile
    container_name: red-app
    networks:
      traffic-light:

  yellow-app:
    build:
      context: ./yellow
      dockerfile: Dockerfile
    container_name: yellow-app
    networks:
      traffic-light:

  green-app:
    build:
      context: ./green
      dockerfile: Dockerfile
    container_name: green-app
    networks:
      traffic-light:

  nginx-proxy:
    image: nginx:1.21
    container_name: nginx-proxy
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
    volumes:
      - ./nginx/proxy:/etc/nginx/conf.d
    networks:
      traffic-light:

networks:
  traffic-light:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
